[package]
name = "trapped"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { path = "../bevy", default-features = false, features = ["bevy_asset", "dynamic_linking"]}
enum_dispatch = "0.3.13"
enumset = "1.1.5"