[package]
name = "bevy_text"
version = "0.15.0"
edition = "2021"
description = "Provides text functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default_font = []

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.15.0" }
bevy_asset = { path = "../bevy_asset", version = "0.15.0" }
bevy_color = { path = "../bevy_color", version = "0.15.1" }
bevy_derive = { path = "../bevy_derive", version = "0.15.0" }
bevy_ecs = { path = "../bevy_ecs", version = "0.15.0" }
bevy_image = { path = "../bevy_image", version = "0.15.0" }
bevy_hierarchy = { path = "../bevy_hierarchy", version = "0.15.0" }
bevy_math = { path = "../bevy_math", version = "0.15.0" }
bevy_reflect = { path = "../bevy_reflect", version = "0.15.0", features = [
  "bevy",
] }
bevy_render = { path = "../bevy_render", version = "0.15.0" }
bevy_sprite = { path = "../bevy_sprite", version = "0.15.0" }
bevy_transform = { path = "../bevy_transform", version = "0.15.0" }
bevy_window = { path = "../bevy_window", version = "0.15.0" }
bevy_utils = { path = "../bevy_utils", version = "0.15.0" }

# other
cosmic-text = { version = "0.12", features = ["shape-run-cache"] }
derive_more = { version = "1", default-features = false, features = [
  "error",
  "from",
  "display",
] }
serde = { version = "1", features = ["derive"] }
smallvec = "1.13"
unicode-bidi = "0.3.13"
sys-locale = "0.3.0"

[dev-dependencies]
approx = "0.5.1"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
