[package]
name = "bevy_ui"
version = "0.15.0"
edition = "2021"
description = "A custom ECS-driven UI framework built specifically for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy
bevy_a11y = { path = "../bevy_a11y", version = "0.15.0" }
bevy_app = { path = "../bevy_app", version = "0.15.0" }
bevy_asset = { path = "../bevy_asset", version = "0.15.0" }
bevy_color = { path = "../bevy_color", version = "0.15.1" }
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.15.0" }
bevy_derive = { path = "../bevy_derive", version = "0.15.0" }
bevy_ecs = { path = "../bevy_ecs", version = "0.15.0" }
bevy_hierarchy = { path = "../bevy_hierarchy", version = "0.15.0" }
bevy_image = { path = "../bevy_image", version = "0.15.0" }
bevy_input = { path = "../bevy_input", version = "0.15.0" }
bevy_math = { path = "../bevy_math", version = "0.15.0" }
bevy_reflect = { path = "../bevy_reflect", version = "0.15.0", features = [
  "bevy",
] }
bevy_render = { path = "../bevy_render", version = "0.15.0" }
bevy_sprite = { path = "../bevy_sprite", version = "0.15.0" }
bevy_text = { path = "../bevy_text", version = "0.15.0" }
bevy_picking = { path = "../bevy_picking", version = "0.15.0", optional = true }
bevy_transform = { path = "../bevy_transform", version = "0.15.0" }
bevy_window = { path = "../bevy_window", version = "0.15.0" }
bevy_utils = { path = "../bevy_utils", version = "0.15.0" }

# other
taffy = { version = "0.5" }
serde = { version = "1", features = ["derive"], optional = true }
bytemuck = { version = "1.5", features = ["derive"] }
derive_more = { version = "1", default-features = false, features = [
  "error",
  "from",
  "display",
] }
nonmax = "0.5"
smallvec = "1.11"
accesskit = "0.17"

[features]
serialize = ["serde", "smallvec/serde", "bevy_math/serialize"]
bevy_ui_picking_backend = ["bevy_picking"]

# Experimental features
ghost_nodes = []

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
